spring:
  datasource:
    url: jdbc:mysql://localhost:3306/workflow_service?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: zhuzhiyang
    driver-class-name: com.mysql.jdbc.Driver
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
  main:
    allow-bean-definition-overriding: true
  activiti:
    database-schema: ACTIVITI
    database-schema-update: true
    history-level: full
    db-history-used: true
    check-process-definitions: false
    async-executor-activate: true


choerodon:
  saga:
    consumer:
      thread-num: 5  # 消费线程数
      poll-interval: 3 # 拉取消息的间隔(秒)，默认1秒
      enabled: false # 是否启用消费端
      core-thread-num: 5
      max-thread-num: 10
  schedule:
    consumer:
      enabled: false # 启用任务调度消费端
      thread-num: 1 # 任务调度消费线程数
      poll-interval-ms: 1000 # 拉取间隔，默认1000毫秒
eureka:
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 3
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
    registryFetchIntervalSeconds: 1
mybatis:
  mapperLocations: classpath*:/mapper/*.xml
  configuration:
    mapUnderscoreToCamelCase: true
feign:
  hystrix:
    shareSecurityContext: true
    command:
      default:
        execution:
          isolation:
            thread:
              timeoutInMilliseconds: 30000
ribbon:
  ConnectTimeout: 50000
  ReadTimeout: 50000

asgard-servie:
  ribbon:
    ConnectTimeout: 50000
    ReadTimeout: 50000
logging:
  level:
    io.choerodon.event.consumer: debug
    com.zaxxer: debug