spring:
  datasource:
    url: jdbc:mysql://localhost:3306/workflow_service?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: zhuzhiyang
    driver-class-name: com.mysql.cj.jdbc.Driver
  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true
  main:
    allow-bean-definition-overriding: true
  activiti:
    database-schema: ACTIVITI
    database-schema-update: true
    history-level: full
    db-history-used: true
    check-process-definitions: false
    async-executor-activate: true
choerodon:
  saga:
    service: choerodon-asgard
    consumer:
      core-thread-num: 20
      max-thread-num:  20 # 消费线程数
      poll-interval: 3 # 拉取消息的间隔(秒)，默认1秒
      enabled: true # 是否启用消费端
  schedule:
    consumer:
      enabled: true # 启用任务调度消费端
      thread-num: 1 # 任务调度消费线程数
      poll-interval-ms: 1000 # 拉取间隔，默认1000毫秒
hzero:
  service:
    platform:
      name: choerodon-platform
    oauth:
      name: choerodon-oauth
    iam:
      name: choerodon-iam
    file:
      name: choerodon-file
    message:
      name: choerodon-message
    admin:
      name: choerodon-admin
    swagger:
      name: choerodon-swagger
    gateway:
      name: choerodon-gateway
    monitor:
      name: choerodon-monitor
eureka:
  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 3
    # 服务的一些元数据信息
    metadata-map:
      VERSION: 0.24.0
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/
    registryFetchIntervalSeconds: 1
mybatis:
  mapperLocations: classpath*:/mapper/*.xml
  configuration:
    mapUnderscoreToCamelCase: true

hystrix:
  threadpool:
    default:
      coreSize: 1000
      maximumSize: 1000
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 70000

ribbon:
  ReadTimeout: 30000
  ConnectTimeout: 1000
  OkToRetryOnAllOperations: true
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 1
logging:
  level:
    io.choerodon.event.consumer: debug
    com.zaxxer: debug